/**
 * Bundled demo content (compiled in — fully offline, no fetch). The English
 * sample exercises the demo pack's toy dictionary; the zh/vi samples show
 * pre-baked hover (and the Hán-Việt bridge) working with no language pack at
 * all, since unknown words are resolved at generation time.
 */
import type { PreparedContent } from "@tsumugu/engine";

import type { TranscriptDoc } from "./reader/sync.js";

const en: PreparedContent = {
  schema: "tsumugu/prepared-content@1",
  lang: "demo",
  title: "Demo (English) — hello world",
  source: "bundled",
  ciTarget: 0.95,
  tokens: [
    { text: "hello", isWord: true },
    { text: " ", isWord: false },
    { text: "world", isWord: true },
    { text: ", ", isWord: false },
    { text: "this", isWord: true },
    { text: " ", isWord: false },
    { text: "is", isWord: true },
    { text: " ", isWord: false },
    { text: "a", isWord: true },
    { text: " ", isWord: false },
    { text: "demo", isWord: true },
    { text: ".", isWord: false },
  ],
  glossary: {
    demo: {
      term: "demo",
      gloss: "a demonstration",
      explanation: "A short example that shows how something works.",
      examples: ["this is a demo."],
    },
    this: { term: "this", gloss: "the thing here" },
  },
};


const vi: PreparedContent = {
  schema: "tsumugu/prepared-content@1",
  lang: "vi",
  title: "Phát triển — vi through zh",
  source: "bundled",
  ciTarget: 0.95,
  tokens: [
    { text: "Việt Nam", isWord: true },
    { text: " ", isWord: false },
    { text: "đang", isWord: true },
    { text: " ", isWord: false },
    { text: "phát triển", isWord: true },
    { text: " ", isWord: false },
    { text: "nhanh", isWord: true },
    { text: ".", isWord: false },
  ],
  glossary: {
    "phát triển": {
      term: "phát triển",
      gloss: "to develop; to grow",
      reading: "phát triển",
      pos: "verb",
      explanation:
        "Sino-Vietnamese (Hán-Việt). You already know Chinese 發展: 發 phát = emit, 展 triển = unfold → develop.",
      examples: ["Việt Nam đang phát triển nhanh."],
      bridge: {
        bridgeLang: "zh-Hant",
        etymon: "發展",
        bridgeReading: "fā zhǎn / ㄈㄚ ㄓㄢˇ",
        meaning: "to develop; development",
        confidence: 0.95,
        corrected: false,
        morphemes: [
          { surface: "phát", etymon: "發", reading: "fā", gloss: "emit; set out" },
          { surface: "triển", etymon: "展", reading: "zhǎn", gloss: "unfold; extend" },
        ],
      },
    },
    đang: {
      term: "đang",
      gloss: "(progressive marker) currently …-ing",
      reading: "đang",
      pos: "particle",
      explanation: "Đặt trước động từ để chỉ hành động đang xảy ra (giống 正在).",
    },
  },
};


const zhNight: PreparedContent = {
  schema: "tsumugu/prepared-content@1",
  lang: "zh-Hant",
  title: "夜市 — 台灣夜市的一個晚上",
  source: "bundled",
  ciTarget: 0.95,
  tokens: [
    { text: "今晚", isWord: true },
    { text: "我們", isWord: true },
    { text: "一起", isWord: true },
    { text: "去", isWord: true },
    { text: "逛", isWord: true },
    { text: "夜市", isWord: true },
    { text: "。", isWord: false },
    { text: "一", isWord: true },
    { text: "走", isWord: true },
    { text: "進去", isWord: true },
    { text: "，", isWord: false },
    { text: "就", isWord: true },
    { text: "聞到", isWord: true },
    { text: "各種", isWord: true },
    { text: "小吃", isWord: true },
    { text: "的", isWord: true },
    { text: "香味", isWord: true },
    { text: "。", isWord: false },
    { text: "街道", isWord: true },
    { text: "兩邊", isWord: true },
    { text: "都", isWord: true },
    { text: "是", isWord: true },
    { text: "攤位", isWord: true },
    { text: "，", isWord: false },
    { text: "人", isWord: true },
    { text: "非常", isWord: true },
    { text: "多", isWord: true },
    { text: "，", isWord: false },
    { text: "很", isWord: true },
    { text: "熱鬧", isWord: true },
    { text: "。", isWord: false },
    { text: "我們", isWord: true },
    { text: "先", isWord: true },
    { text: "買", isWord: true },
    { text: "了", isWord: true },
    { text: "一", isWord: true },
    { text: "杯", isWord: true },
    { text: "珍珠奶茶", isWord: true },
    { text: "，", isWord: false },
    { text: "邊", isWord: true },
    { text: "走", isWord: true },
    { text: "邊", isWord: true },
    { text: "喝", isWord: true },
    { text: "。", isWord: false },
    { text: "朋友", isWord: true },
    { text: "說", isWord: true },
    { text: "他", isWord: true },
    { text: "最", isWord: true },
    { text: "喜歡", isWord: true },
    { text: "這裡", isWord: true },
    { text: "的", isWord: true },
    { text: "臭豆腐", isWord: true },
    { text: "。", isWord: false },
    { text: "雖然", isWord: true },
    { text: "味道", isWord: true },
    { text: "很", isWord: true },
    { text: "特別", isWord: true },
    { text: "，", isWord: false },
    { text: "但是", isWord: true },
    { text: "吃", isWord: true },
    { text: "起來", isWord: true },
    { text: "其實", isWord: true },
    { text: "很", isWord: true },
    { text: "香", isWord: true },
    { text: "。", isWord: false },
    { text: "我們", isWord: true },
    { text: "又", isWord: true },
    { text: "玩", isWord: true },
    { text: "了", isWord: true },
    { text: "幾", isWord: true },
    { text: "個", isWord: true },
    { text: "遊戲", isWord: true },
    { text: "，", isWord: false },
    { text: "還", isWord: true },
    { text: "贏", isWord: true },
    { text: "了", isWord: true },
    { text: "一", isWord: true },
    { text: "個", isWord: true },
    { text: "小", isWord: true },
    { text: "娃娃", isWord: true },
    { text: "。", isWord: false },
    { text: "走", isWord: true },
    { text: "累", isWord: true },
    { text: "了", isWord: true },
    { text: "，", isWord: false },
    { text: "就", isWord: true },
    { text: "坐", isWord: true },
    { text: "在", isWord: true },
    { text: "路邊", isWord: true },
    { text: "休息", isWord: true },
    { text: "一下", isWord: true },
    { text: "。", isWord: false },
    { text: "看", isWord: true },
    { text: "著", isWord: true },
    { text: "來來往往", isWord: true },
    { text: "的", isWord: true },
    { text: "人", isWord: true },
    { text: "，", isWord: false },
    { text: "我", isWord: true },
    { text: "覺得", isWord: true },
    { text: "很", isWord: true },
    { text: "放鬆", isWord: true },
    { text: "。", isWord: false },
    { text: "這", isWord: true },
    { text: "就是", isWord: true },
    { text: "台灣", isWord: true },
    { text: "夜市", isWord: true },
    { text: "的", isWord: true },
    { text: "魅力", isWord: true },
    { text: "。", isWord: false },
  ],
  glossary: {
    "逛": {
      term: "逛",
      gloss: "to stroll; to wander around",
      reading: "ㄍㄨㄤˋ / guàng",
      pos: "verb",
      level: "TOCFL-A2",
      explanation: "沒有特定目標地走來走去、看看東西，例如逛街、逛夜市。",
      examples: ["今晚我們一起去逛夜市。"],
    },
    "夜市": {
      term: "夜市",
      gloss: "night market",
      reading: "ㄧㄝˋ ㄕˋ / yè shì",
      pos: "noun",
      level: "TOCFL-A2",
      explanation: "晚上才開的市場，可以一邊走一邊吃東西、買東西，通常很熱鬧。",
      examples: ["今晚我們一起去逛夜市。"],
    },
    "進去": {
      term: "進去",
      gloss: "to go in; to enter",
      reading: "ㄐㄧㄣˋ ㄑㄩˋ / jìn qù",
      pos: "verb",
      level: "TOCFL-A1",
      explanation: "從外面走到裡面。相反是「出來」。",
      examples: ["一走進去，就聞到各種小吃的香味。"],
    },
    "聞到": {
      term: "聞到",
      gloss: "to smell (and notice) something",
      reading: "ㄨㄣˊ ㄉㄠˋ / wén dào",
      pos: "verb",
      level: "TOCFL-A2",
      explanation: "用鼻子感覺到味道。「到」表示真的感覺到了。",
      examples: ["一走進去，就聞到各種小吃的香味。"],
    },
    "各種": {
      term: "各種",
      gloss: "all kinds of; various",
      reading: "ㄍㄜˋ ㄓㄨㄥˇ / gè zhǒng",
      pos: "determiner",
      level: "TOCFL-B1",
      explanation: "很多不同的種類。例如各種小吃、各種顏色。",
      examples: ["一走進去，就聞到各種小吃的香味。"],
    },
    "小吃": {
      term: "小吃",
      gloss: "snacks; street food",
      reading: "ㄒㄧㄠˇ ㄔ / xiǎo chī",
      pos: "noun",
      level: "TOCFL-A2",
      explanation: "份量小、價格便宜的食物，常在夜市或路邊賣。",
      examples: ["一走進去，就聞到各種小吃的香味。"],
    },
    "香味": {
      term: "香味",
      gloss: "a pleasant smell; aroma",
      reading: "ㄒㄧㄤ ㄨㄟˋ / xiāng wèi",
      pos: "noun",
      level: "TOCFL-B1",
      explanation: "好聞的味道，例如食物或花的香味。",
      examples: ["一走進去，就聞到各種小吃的香味。"],
    },
    "街道": {
      term: "街道",
      gloss: "street",
      reading: "ㄐㄧㄝ ㄉㄠˋ / jiē dào",
      pos: "noun",
      level: "TOCFL-A2",
      explanation: "城市裡讓人和車走的路。",
      examples: ["街道兩邊都是攤位，人非常多，很熱鬧。"],
    },
    "攤位": {
      term: "攤位",
      gloss: "a (market) stall; vendor's booth",
      reading: "ㄊㄢ ㄨㄟˋ / tān wèi",
      pos: "noun",
      level: "TOCFL-B1",
      explanation: "在市場或路邊賣東西的小桌子或小店。",
      examples: ["街道兩邊都是攤位，人非常多，很熱鬧。"],
    },
    "非常": {
      term: "非常",
      gloss: "extremely; very",
      reading: "ㄈㄟ ㄔㄤˊ / fēi cháng",
      pos: "adverb",
      level: "TOCFL-A2",
      explanation: "程度很高，比「很」更強。",
      examples: ["街道兩邊都是攤位，人非常多，很熱鬧。"],
    },
    "熱鬧": {
      term: "熱鬧",
      gloss: "lively; bustling",
      reading: "ㄖㄜˋ ㄋㄠˋ / rè nào",
      pos: "adjective",
      level: "TOCFL-B1",
      explanation: "人多、聲音多、很有活力的樣子，跟「安靜」相反。",
      examples: ["街道兩邊都是攤位，人非常多，很熱鬧。"],
    },
    "珍珠奶茶": {
      term: "珍珠奶茶",
      gloss: "bubble (pearl milk) tea",
      reading: "ㄓㄣ ㄓㄨ ㄋㄞˇ ㄔㄚˊ / zhēn zhū nǎi chá",
      pos: "noun",
      level: "TOCFL-A2",
      explanation: "加了珍珠（QQ 的小圓球）的奶茶，是台灣很有名的飲料。",
      examples: ["我們先買了一杯珍珠奶茶，邊走邊喝。"],
    },
    "臭豆腐": {
      term: "臭豆腐",
      gloss: "stinky tofu",
      reading: "ㄔㄡˋ ㄉㄡˋ ㄈㄨˇ / chòu dòu fǔ",
      pos: "noun",
      level: "TOCFL-B1",
      explanation: "一種味道很重的豆腐，聞起來臭、吃起來香，是夜市名菜。",
      examples: ["朋友說他最喜歡這裡的臭豆腐。"],
    },
    "味道": {
      term: "味道",
      gloss: "taste; smell; flavor",
      reading: "ㄨㄟˋ ㄉㄠˋ / wèi dào",
      pos: "noun",
      level: "TOCFL-A2",
      explanation: "食物的味道，也可以指聞到的氣味。",
      examples: ["雖然味道很特別，但是吃起來其實很香。"],
    },
    "特別": {
      term: "特別",
      gloss: "special; particularly",
      reading: "ㄊㄜˋ ㄅㄧㄝˊ / tè bié",
      pos: "adjective",
      level: "TOCFL-A2",
      explanation: "跟一般的不一樣；也可以當副詞，表示「尤其」。",
      examples: ["雖然味道很特別，但是吃起來其實很香。"],
    },
    "其實": {
      term: "其實",
      gloss: "actually; in fact",
      reading: "ㄑㄧˊ ㄕˊ / qí shí",
      pos: "adverb",
      level: "TOCFL-A2",
      explanation: "用來說出跟別人想的不一樣的真實情況。",
      examples: ["雖然味道很特別，但是吃起來其實很香。"],
    },
    "遊戲": {
      term: "遊戲",
      gloss: "game",
      reading: "ㄧㄡˊ ㄒㄧˋ / yóu xì",
      pos: "noun",
      level: "TOCFL-A2",
      explanation: "為了好玩而做的活動，例如夜市的射氣球、套圈圈。",
      examples: ["我們又玩了幾個遊戲，還贏了一個小娃娃。"],
    },
    "贏": {
      term: "贏",
      gloss: "to win",
      reading: "ㄧㄥˊ / yíng",
      pos: "verb",
      level: "TOCFL-A2",
      explanation: "在比賽或遊戲中得到勝利，相反是「輸」。",
      examples: ["我們又玩了幾個遊戲，還贏了一個小娃娃。"],
    },
    "娃娃": {
      term: "娃娃",
      gloss: "doll",
      reading: "ㄨㄚˊ ㄨㄚˊ / wá wá",
      pos: "noun",
      level: "TOCFL-A2",
      explanation: "小孩玩的人形玩具，夜市遊戲常拿來當獎品。",
      examples: ["我們又玩了幾個遊戲，還贏了一個小娃娃。"],
    },
    "路邊": {
      term: "路邊",
      gloss: "roadside; by the road",
      reading: "ㄌㄨˋ ㄅㄧㄢ / lù biān",
      pos: "noun",
      level: "TOCFL-A2",
      explanation: "路的旁邊。",
      examples: ["走累了，就坐在路邊休息一下。"],
    },
    "休息": {
      term: "休息",
      gloss: "to rest; to take a break",
      reading: "ㄒㄧㄡ ㄒㄧ / xiū xī",
      pos: "verb",
      level: "TOCFL-A1",
      explanation: "停下來不做事，讓身體放鬆一下。",
      examples: ["走累了，就坐在路邊休息一下。"],
    },
    "來來往往": {
      term: "來來往往",
      gloss: "coming and going (of people)",
      reading: "ㄌㄞˊ ㄌㄞˊ ㄨㄤˇ ㄨㄤˇ / lái lái wǎng wǎng",
      pos: "phrase",
      level: "TOCFL-B1",
      explanation: "很多人不停地走過來又走過去的樣子。",
      examples: ["看著來來往往的人，我覺得很放鬆。"],
    },
    "覺得": {
      term: "覺得",
      gloss: "to feel; to think",
      reading: "ㄐㄩㄝˊ ㄉㄜˊ / jué dé",
      pos: "verb",
      level: "TOCFL-A1",
      explanation: "表達自己的感覺或看法。",
      examples: ["看著來來往往的人，我覺得很放鬆。"],
    },
    "放鬆": {
      term: "放鬆",
      gloss: "to relax; relaxed",
      reading: "ㄈㄤˋ ㄙㄨㄥ / fàng sōng",
      pos: "verb",
      level: "TOCFL-B1",
      explanation: "讓心情或身體不緊張、舒服一點。",
      examples: ["看著來來往往的人，我覺得很放鬆。"],
    },
    "台灣": {
      term: "台灣",
      gloss: "Taiwan",
      reading: "ㄊㄞˊ ㄨㄢ / tái wān",
      pos: "proper noun",
      level: "TOCFL-A1",
      explanation: "一個位於東亞的島，夜市文化非常有名。",
      examples: ["這就是台灣夜市的魅力。"],
    },
    "魅力": {
      term: "魅力",
      gloss: "charm; appeal",
      reading: "ㄇㄟˋ ㄌㄧˋ / mèi lì",
      pos: "noun",
      level: "TOCFL-B1",
      explanation: "吸引人的力量，讓人很喜歡的特質。",
      examples: ["這就是台灣夜市的魅力。"],
    },
  },
};

const zhNightTranscript: TranscriptDoc = {
  cues: [
    { text: "今晚我們一起去逛夜市。", start: "00:00:00,000", end: "00:00:03,600", tr: "Tonight the two of us are going to wander the night market together." },
    { text: "一走進去，就聞到各種小吃的香味。", start: "00:00:03,600", end: "00:00:07,200", tr: "The moment you step inside, you catch the smell of every kind of street food." },
    { text: "街道兩邊都是攤位，人非常多，很熱鬧。", start: "00:00:07,200", end: "00:00:10,800", tr: "Both sides of the street are lined with stalls, packed with people — really lively." },
    { text: "我們先買了一杯珍珠奶茶，邊走邊喝。", start: "00:00:10,800", end: "00:00:14,400", tr: "First we bought a cup of bubble tea and sipped it as we walked." },
    { text: "朋友說他最喜歡這裡的臭豆腐。", start: "00:00:14,400", end: "00:00:18,000", tr: "My friend said the stinky tofu here is his favorite." },
    { text: "雖然味道很特別，但是吃起來其實很香。", start: "00:00:18,000", end: "00:00:21,600", tr: "Even though the smell is unusual, it actually tastes wonderful." },
    { text: "我們又玩了幾個遊戲，還贏了一個小娃娃。", start: "00:00:21,600", end: "00:00:25,199", tr: "We played a few games too, and even won a little doll." },
    { text: "走累了，就坐在路邊休息一下。", start: "00:00:25,199", end: "00:00:28,800", tr: "When our feet got tired, we sat down by the roadside to rest a while." },
    { text: "看著來來往往的人，我覺得很放鬆。", start: "00:00:28,800", end: "00:00:32,399", tr: "Watching the people coming and going, I felt completely at ease." },
    { text: "這就是台灣夜市的魅力。", start: "00:00:32,399", end: "00:00:36,000", tr: "This, right here, is the charm of a Taiwan night market." },
  ],
  sections: [
    { start: "00:00:00,000", end: "00:00:36,000", title: "夜市的一個晚上", summary: "朋友兩個人晚上一起去逛台灣的夜市，吃小吃、喝珍珠奶茶、玩遊戲，最後坐在路邊休息，覺得很放鬆。", tr: "Two friends spend an evening at a Taiwan night market — street food, bubble tea, games, and a relaxed rest by the roadside." },
  ],
};

export interface Sample {
  id: string;
  label: string;
  content: PreparedContent;
  /** Optional timed transcript → mounts the synced-reader panel. */
  transcript?: TranscriptDoc;
}

export const SAMPLES: Sample[] = [
  { id: "zh-night", label: "中文 — 夜市 (zh-Hant)", content: zhNight, transcript: zhNightTranscript },
  { id: "en", label: "Demo (English)", content: en },
  { id: "vi", label: "Tiếng Việt — phát triển", content: vi },
];
